image: jguyomard/hugo-builder:0.31-extras

variables:
  BUILD_DIR: "build"
  CLOUDSDK_BIN_PATH: "/root/google-cloud-sdk/bin"
  CLOUDSDK_CORE_DISABLE_PROMPTS: "yes"
  GCS_BUCKET: "sites.monax.io"

before_script:
- |
  apk --update --no-cache add bash
  # [csk] I know, I know, but you try it without.... vvv
  curl -sSL https://sdk.cloud.google.com | bash &>/dev/null
  echo $GCS_CLIENT_SECRET > client-secret.json
  $CLOUDSDK_BIN_PATH/gcloud auth activate-service-account --key-file client-secret.json
  rm client-secret.json

.deploy_template: &deploy_template
  stage: deploy
  script:
  - |
    hugo \
      --verbose \
      --canonifyURLs \
      --cleanDestinationDir \
      --forceSyncStatic \
      --destination=$BUILD_DIR \
      --baseURL="https://$SITE_NAME"
    minify \
      --verbose \
      --html-keep-document-tags \
      --recursive \
      --output \
      $BUILD_DIR/ $BUILD_DIR/
    $CLOUDSDK_BIN_PATH/gsutil -m \
      rsync -r -d \
      $BUILD_DIR gs://$GCS_BUCKET/$SITE_NAME

deploy_production:
  only:
    - master
  environment:
    name: production
    url: https://agreements.network
  variables:
    SITE_NAME: "agreements.network"
  <<: *deploy_template

deploy_staging:
  only:
    - develop
  environment:
    name: staging
    url: https://staging.agreements.network
  variables:
    SITE_NAME: "staging.agreements.network"
  <<: *deploy_template
