image: jguyomard/hugo-builder:0.26-extras

variables:
  BUILD_DIR: "build"
  S3_BUCKET: "sites.monax.io"
  SITE_NAME: "agreements.network"

before_script:
- apk --update --no-cache add python py-pip
- pip install --upgrade awscli

.deploy_template: &deploy_template
  stage: deploy
  script:
  - hugo --destination $BUILD_DIR --baseURL "https://$SITE_NAME"
  #- minify -r -o $BUILD_DIR/ $BUILD_DIR/
  - aws s3 sync $BUILD_DIR s3://$S3_BUCKET/$SITE_NAME --acl public-read --delete
  cache:
    untracked: true
    key: "$CI_COMMIT_REF_NAME"
    paths:
    - build

deploy_production:
  only:
    - master
  environment:
    name: production
    url: https://agreements.network
  <<: *deploy_template

deploy_staging:
  only:
    - develop
  environment:
    name: staging
    url: https://staging.agreements.network
  variables:
    SITE_NAME: "agreements.network"
  <<: *deploy_template
