image: jguyomard/hugo-builder:0.26-extras

before_script:
- BUILD_DIR="/tmp/build"
- S3_BUCKET="sites.monax.io"
- SITE_NAME="agreements.network"
- apk --update --no-cache add python py-pip
- pip install --upgrade awscli s3cmd python-magic

deploy:
  script:
  - aws configure list # tmp
  - hugo --destination $BUILD_DIR
  - minify -r -o $BUILD_DIR/ $BUILD_DIR/
  - aws s3 sync $BUILD_DIR s3://$S3_BUCKET/$SITE_NAME
  cache:
    paths:
    - $BUILD_DIR
