image: jguyomard/hugo-builder:0.40-extras

stages:
- build
- deploy

before_script:
- git submodule init && git submodule update

variables:
  GCS_BUCKET: "sites.monax.io"
  BUILD_DIR: "./build"

# Variable packages
.variables_staging: &vars_staging
  only:
    - staging@success/agreements.network
  variables:
    SITE_NAME: "staging.agreements.network"

.variables_production: &vars_production
  only:
    - production@success/agreements.network
  variables:
    SITE_NAME: "agreements.network"

# Job templates
.build_site_template: &build_template
  stage: build
  script:
    - |
      hugo \
        --verbose \
        --destination=$BUILD_DIR \
        --baseURL="https://$SITE_NAME" &&
      minify \
        --verbose \
        --html-keep-document-tags \
        --recursive \
        --output \
        $BUILD_DIR/ $BUILD_DIR/
  artifacts:
    paths:
      - $BUILD_DIR

# Build jobs
build staging:
  <<: *vars_staging
  <<: *build_template

build production:
  <<: *vars_production
  <<: *build_template

.deploy_template: &deploy_template
  stage: deploy
  image: quay.io/monax/build:latest
  before_script:
    - |
      echo $GCS_CLIENT_SECRET_SITES > client-secret.json
      gcloud auth activate-service-account --key-file client-secret.json
      rm client-secret.json
  script:
    - gsutil -m rsync -r -d build gs://$GCS_BUCKET/$SITE_NAME

# Deploy jobs
deploy staging:
  environment:
    name: staging
    url: https://staging.agreements.network
  dependencies:
    - build staging
  <<: *vars_staging
  <<: *deploy_template

# Deploy jobs
deploy production:
  stage: deploy
  image: quay.io/monax/build:latest
  dependencies:
    - build production
  only:
    - production@success/agreements.network
  before_script:
    - |
      eval $(ssh-agent -s) && \
      echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null && \
      mkdir -p $HOME/.ssh && chmod 700 $HOME/.ssh && \
      echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config && \
      git config --global user.name "Billings, a Bot" && \
      git config --global user.email "billings@monax.io" && \
      git clone git@github.com:agreements-network/site build-base
  script:
    - |
      cp -r build/* build-base
      cd build-base
      git add -A :/
      git commit -m "Automatic document generation: $CI_COMMIT_SHA"
      git push origin master
