# Page settings
baseurl = "localhost:1313"
title = "Agreements Network"
languageCode = "en-us"
theme = "elate"


[params]

  custom_css = ["css/custom.css"]

  # Meta
  author = ""
  description = ""
  email = ""
  # Navigation
  [params.navigation]
    logo = "AgreementsNetwork_logo.png"
    brand = "Agreements Network"

    # home = "Home"
    overview = "Platform"
    whitepaper = "Whitepaper"
    usecases = "Use Cases"
    faq = "FAQ"
    contact = "Contact"

    # You can add custom links before or after the default links
    # Assign a weight to define the order

    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    [[menu.postpend]]
     url = "https://docs.agreements.network/"
     name = "Docs"
     weight = 10

  # Hero section
  [params.hero]
    title = "The Agreements Network"
    subtitle = "Introducing a decentralized contract management platform that uses smart contract technology to create, prove and operate legal agreements.<br><span class='white'>It's the legal layer for a networked world.</span>"
    textureimg = "agreements-network-texture.png"

  [params.hero.video]
    enable = true
    icon = "icon-play2"
    button = "Watch the video"
    url = "https://vimeo.com/channels/staffpicks/93951774"

  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "For Lawyers"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
    url = "#"
    external = false
    sectionLink = "usecases"
    button = "Read Use Cases"
    icon = "icon-key"
    # img = ""

  [[params.intro.item]]
    title = "For Businesses"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
    url = "#"
    external = false
    sectionLink = "usecases"
    button = "Read Use Cases"
    icon = "icon-chart"
    # img = ""

  [[params.intro.item]]
    title = "For Developers"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
    url = "https://docs.agreements.network/"
    external = true
    sectionLink = ""
    button = "Read The Docs"
    icon = "icon-rocket"
    # img = ""

  # overview section
  [params.overview]
    enable = true
    title = "Overview"
    # description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.overview.col1]]
      title = "The Problem"
      description = "Contracts are fundamental to the global economic system, yet the way agreements are formed and monitored is slow and costly. The market is failing to be effectively served by a legal establishment geared towards the bespoke and high-value. Growing markets such as the networked economy need a way to access better legal services and tools that support the way modern commerce is evolving."

    [[params.overview.col2]]
      title = "The Solution"
      description = "The Agreements Network is built to enable new and more efficient forms of reaching agreement via decentralised, distributed systems. It provides a technical platform enabling lawyers to productise their previously bespoke services into legal products. It uses state-of-the-art blockchain and smart contracts technologies to provide consumers with . It is the legal layer for the networked world.<br><br>The Network allows users to build, repurpose and operate legal agreements with the click of a few buttons. Network users are stakeholders in the platform, rewarded for their contributions while building their own value-added revenue streams."


  # overview section
  [params.whitepaper]
    enable = true
    title = "Whitepaper"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.whitepaper.item]]
      title = "Download Our Whitepaper"
      description = "The Agreements Network shifts the paradigm from bespoke legal services to scalable, repeatable legal products. The commoditization of legal services benefits both legal producers and the consumers of their services, via a secure token-based ecosystem. The Agreements Network leverages the liquid expectation of digital service delivery lifting legal services onto the same playing field and making it an accessible tool."
      docimg = "AN-Whitepaper-cover.gif"
      button = "Download Whitepaper"
      url = "#"

  # overview section
  [params.usecases]
    enable = true
    title = "Use Cases"
    # description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."


    [[params.usecases.item]]
      title = "Legal Template Producers"
      subtitle = "Making money building better legal operations"
      description = "<p>Active Agreements create a new method for legal services professionals to serve existing clients while building additional revenue streams and smarter networked operations.</p><p>Using Active Agreements, lawyers can create legally-effective smart contracts to serve their clients better and make more money. The Agreements Network contains the building blocks of automated legal operations. Using the Agreements Network, lawyers can assemble legal prose and workflow “Archetypes” that create, formalize, store and prove client contract rights.</p>"
      img = "agreements-network-diagram-05.png"
      alt = "Legal Template Producers"

    [[params.usecases.item]]
      title = "Corporate Governance"
      subtitle = "Increasing Margins through Functionality and Reproducability"
      description = "<p>Corporate governance, the system of rules and processes which control a company, is a significant workstream for lawyers. The beginning of this process is incorporation or organization of a company. Incorporation of a business is one of the most common processes in legal operations, with more than 250,000 new limited liability companies and corporations organizing each quarter in the United States alone. Articles of organization are a necessary dependency for most businesses - the first step to hiring an employee and opening a business bank account, for example.</p><p>The Agreements Network provides value by creating a persistent record of the incorporation instrument, to anchor further smart contracts for corporate governance like bylaws, equity, and operations contracts.</p>"
      img = "agreements-network-diagram-05.png"
      alt = "Corporate Governance"

    [[params.usecases.item]]
      title = "Equipment Leasing - Fleets"
      subtitle = "Facilitating As-A-Service Business Models"
      description = "<p>In the evolving network economy, devices upgrade and proliferate quickly, meaning less incentive to buy a device and keep it for years and more pay-per-use and leasing models. This corresponds to an increase in deployments of fleets of equipment, for example, solar panels, electric car chargers and robotics like drones.</p><img src='images/agreements-network-diagram-08.png' alt='Equipment Leasing - Fleets'>"
      img = "agreements-network-diagram-06.png"
      alt = "Equipment Leasing - Fleets"

    [[params.usecases.item]]
      title = "Content Creators"
      subtitle = "Earning Money While Protecting Content Rights"
      description = "<p>The internet has disrupted traditional media channels and built new ones for users to create and distribute content. These new channels bring with them problems for creators of unique content, for example video producers on platforms like YouTube.</p><p>These boundless opportunities for content creators attach complex legal challenges. Content creators in network commerce struggle in three main ways: maintaining ownership of their intellectual property (IP), ensuring fair remuneration for their content, and protecting against the prospect of third-party copyright infringement lawsuits. The Agreements Network is a powerful tool to meet these unique challenges.</p>"
      img = "agreements-network-diagram-07.png"
      alt = "Content Creators"


  # overview section
  [params.faq]
    enable = true
    title = "FAQ"
    # description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.faq.section1]]
      title = "Basics"

      [[params.faq.section1item]]
        question = "What is the Agreements Network?"
        answer = "No text yet"

      [[params.faq.section1item]]
        question = "Where's your whitepaper?"
        answer = "No text yet"

      [[params.faq.section1item]]
        question = "Where's your technical (yellow) paper?"
        answer = "No text yet"

      [[params.faq.section1item]]
        question = "Where's your governance (orange) paper?"
        answer = "No text yet"

    [[params.faq.section2]]
      title = "Basics of Agreements"

    [[params.faq.section2item]]
      question = "Why do people want to enter into agreements at all?"
      answer = "Certainty over whether an agreement was made<br>Clarity between parties about the specifics of what was agreed<br>Benefits/consideration agreed<br>Mechanisms/rules of transaction<br>Greater efficiency in resolving disputes<br>Enforceability - ambient legal structures allow the weak to trust the strong"

    [[params.faq.section2item]]
      question = "Why do people (or other autonomous entities) stand to gain by entering into an agreement digitally?"
      answer = "Computable reference object (could drive automation elsewhere)<br>Cryptographic proof of agreement state (by parties timestamping, signing it, ordering it amongst other documents by hash-chaining)<br>Security against loss<br>Interaction with other agreements (e.g. static hierarchical, or dynamic with respect to state change)<br>Updateability or freshness<br>Fulfilment logs and other event streams"

    [[params.faq.section3]]
      title = "Basics of Network"

    [[params.faq.section3item]]
      question = "What is the Agreements Network built on?"
      answer = "No text yet"

    [[params.faq.section3item]]
      question = "What is Cosmos?"
      answer = "No text yet"

    [[params.faq.section3item]]
      question = "Why is the Agreements Network not built on Ethereum?"
      answer = "No text yet"

    [[params.faq.section3item]]
      question = "What is the permissioning model of the Agreements Network?"
      answer = "No text yet"

    [[params.faq.section3item]]
      question = "How do I become a validator of the Agreements Network?"
      answer = "No text yet"


    [[params.faq.section4]]
      title = "Basics of the Agreements Network's Protocol"

    [[params.faq.section4item]]
      question = "I'm a lawyer, how can I make money by using the Agreements Network?"
      answer = "No text yet"

    [[params.faq.section4item]]
      question = "I'm a smart contract developer, how can I build things for the Agreements Network?"
      answer = "No text yet"

    [[params.faq.section4item]]
      question = "I'm a service provider for various ethereum systems, how can I integrate my services into the Agreements Network?"
      answer = "No text yet"


    [[params.faq.section5]]
      title = "Token Economics"

    [[params.faq.section5item]]
      question = "Why do you have a token?"
      answer = "No text yet"

    [[params.faq.section5item]]
      question = "What does your token do?"
      answer = "No text yet"

    [[params.faq.section5item]]
      question = "When is your ICO?"
      answer = "No text yet"

    [[params.faq.section5item]]
      question = "When is your presale?"
      answer = "No text yet"

    [[params.faq.section5item]]
      question = "What is the distribution of the token on network launch?"
      answer = "No text yet"

    [[params.faq.section5item]]
      question = "What will the price of the token be in 1, 3, 5 years?"
      answer = "No text yet"

    [[params.faq.section5item]]
      question = "I'm a US based token purchaser, can I buy your token?"
      answer = "No text yet"

  # Contact section
  [params.contact]
    enable = true
    map = false
    form = true
    title = "Get In Touch"
    # description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
    
    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "44 Malborough Street, London,<br>W1F7JL, United Kingdom"],
        # ["icon-phone", "(123) 465-6789"],
        ["icon-envelope", "<a href='mailto:contact@monax.io' alt='contact@monax.io'>contact@monax.io</a>"],
        ["icon-globe", '<a href="/" target="">agreements.network</a>']
      ]

    fname = "First Name"
    lname = "Last Name"
    email = "Email"
    button = "Subscribe To Updates"

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; Monax Industries 2018. All Rights Reserved.'
    links = [
        ["icon-twitter", "https://twitter.com/monaxhq"],
        ["icon-facebook", "https://www.facebook.com/monaxHQ/"],
        # ["icon-youtube", "#youtube"]
      ]
